import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function TopBar() {
    return (
        <div id="top-bar-box">
            <div id="top-bar-content" className="layout horiz">
                <a href="">
                    <img src=""/>
                </a>
                <div className="layout horiz">
                    <h4>Matches</h4>
                    <h4>Events</h4>
                    <h4>Spoilers Toggle</h4>
                    <h4>Log In</h4>
                </div>
            </div>
        </div>
    )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <header><TopBar/></header>
      <body>{children}</body>
    </html>
  );
}
